name: Hprofile Action
on: workflow_dispatch
jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code clone
        uses: actions/checkout@v4

      - name : Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
        
